name: Lint
on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: [18]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Linting files
        run: npm run lint
      - name: Typechecking typescripts files
        run: npm run typecheck
